### ISSUE TITLE
Cannot download blob

### ISSUE THREAD

**Issue by LucasHarvey** [xbrianh/gs-chunked-io#19]
I get the following error when doing 
`with gscio.Reader(blob) as fh:
        yield fh.read(1024)`
(as suggested in the docs):

`download_as_string() got an unexpected keyword argument 'start'`

**Comment by xbrianh** [comment]
Thanks for trying my library!

My first thought is you may by using an older version of `google-cloud-storage`  than I used during development. If you upgrade I suspect your code snippet may work (it did for me). 

I'll probably pin google-cloud-storage >= 1.26.0, see https://github.com/xbrianh/gs-chunked-io/pull/22

**Comment by xbrianh** [comment]
Closed via #22
